chore(cf-gha-baseline): add PR branch/repo name check for security reasons

diff --git a/actions/cf-gha-baseline/action.yaml b/actions/cf-gha-baseline/action.yaml
--- a/actions/cf-gha-baseline/action.yaml
+++ b/actions/cf-gha-baseline/action.yaml
@@ -160,6 +160,11 @@ runs:
 
         case ${GITHUB_EVENT_NAME} in
           pull_request|pull_request_target)
+            if [[ ! "$PR_HEAD_REPO" =~ ^[a-zA-Z0-9._/-]+$ ]] || [[ ! "$PR_HEAD_REF" =~ ^[a-zA-Z0-9._/-]+$ ]];
+            then
+              echo "[!] Invalid PR branch or repo name (!= ^[a-zA-Z0-9._/-]+\$). Aborting for security reasons."
+              exit 1
+            fi
             PUSH_PUBLIC="false"
             TRIGGERING_REF=pr
             BRANCH_NAME=${{ github.event.pull_request.head.ref }}
